var SearchConstants = {
  FETCH_SEARCH: "FETCH_SEARCH",
  CLEAR_RESULTS: "CLEAR_RESULTS",
  FETCH_COMPARISON: "FETCH_COMPARISON",
  CLEAR_COMPARISON: "CLEAR_COMPARISON",
  FETCH_MOST: "FETCH_MOST",
  AUTO_COMPLETE: "AUTO_COMPLETE"

};

module.exports = SearchConstants;
