var StoreConstants = {
  GET_STORE: "GET_STORE",
  GET_COMPARISON: "GET_COMPARISON",
  CLEAR_COMPARISON: "CLEAR_COMPARISON",
  UPDATE_MAP: "UPDATE_MAP",
  FETCH_FILTERS: "FETCH_FILTERS",
  GET_BROWSE: "GET_BROWSE",
  GET_MOST_VISITED: "GET_MOST_VISITED",
  GET_TRENDING: "GET_TRENDING",
  GET_MOST: "GET_MOST",
  USER_LOCATION: "USER_LOCATION"
};

module.exports = StoreConstants;
